### ISSUE TITLE
Module system bug

### ISSUE THREAD

**Issue by thisbefruit** [mel-project/melodeon#19]
Here are the two relevant files in `demo-dir`:

main.melo:
````
require "sorting.melo"

---
bubble_sort([6, 5, 3, 4, 1, 2, 0])
````

sorting.melo:
````
provide bubble_sort

def bubble_sort(vec: [Any;]) =
    vec
````

When I tried to `require` a file in the same directory, the REPL said,
````
❯ melorun -i demo-dir/
Error: Melodeon compilation failed
STDLIB: error: undefined type T-0
````
@nullchinchilla suggested it might be the mangler.

**Comment by nullchinchilla** [comment]
This is fixed in version 0.5.
