### ISSUE TITLE
Panic using 'for' on a nested vector retrieved with vref

### ISSUE THREAD

**Issue by sadministrator** [mel-project/melodeon#21]
An example, `let nested = [[0,1], [2,3], [4,5]] in for val in vref(nested, 1) collect val + 1`, which causes this panic:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/marco/.cargo/registry/src/github.com-1ecc6299db9ec823/melodeon-0.5.11/src/typesys/typecheck.rs:1331:13
```
It seems the panic occurs in [`fn index(&self, idx: Option<&ConstExpr<CVar>>) -> Option<Cow<Self>>`](https://github.com/themeliolabs/melodeon/blob/master/src/typesys/types.rs#L456), maybe the itype of the vector isn't enumerated in the match and it's hitting line [489](https://github.com/themeliolabs/melodeon/blob/master/src/typesys/types.rs#L489)?

**Comment by nullchinchilla** [comment]
This is fixed in bdefb51. Now this correctly returns:
```
cannot compile Melodeon covenant: cannot do comprehension over the type [{0}, {1}] | [{2}, {3}] | [{4}, {5}] | {0}
```

(Note that `vref` returns `T | False`, because it does runtime bounds-checking. If you want compile-time bounds-checking, use `nested[1]`)
